name: deploy-to-server
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenAI baselines
        uses: actions/checkout@v2
        with:
          repository: openai/baselines
          path: baselines
      - name: Checkout keras-rl
        uses: actions/checkout@v2
        with:
          repository: keras-rl/keras-rl
          path: keras-rl
      - name: Checkout the main branch
        uses: actions/checkout@v2
        with:
          path: main
      - name: Prepare workspace for deployment
        run: |
          echo "Moving baselines repo"
          mv ${{ github.workspace }}/baselines/baselines ${{ github.workspace }}/baselines_tmp
          rm -rf ${{ github.workspace }}/baselines
          mv ${{ github.workspace }}/baselines_tmp ${{ github.workspace }}/baselines

          echo "Moving keras-rl repo"
          mv ${{ github.workspace }}/keras-rl/rl ${{ github.workspace }}/

          echo "Moving main repo"
          mv ${{ github.workspace }}/main/* ${{ github.workspace }}/

          rm -rf ${{ github.workspace }}/main/

          echo "Listing files in workspace"
          ls -ltr ${{ github.workspace }}/
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - name: Deploy with rsync
        run: rsync -avz --exclude='.*' --exclude='*cache*' ${{ github.workspace }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DIR }}/